name: Gradle publish to packages.atlassian.com
on:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      # Populates ARTIFACTORY_USERNAME and ARTIFACTORY_API_KEY with
      # temporary username/password for publishing to packages.atlassian.com
      - name: Get publish token
        id: publish-token
        uses: atlassian-labs/artifact-publish-token@v1.0.1
        with:
          output-modes: environment

      # Publishes to Artifactory only on push to the "release" branch.
      - name: "Publish"
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: chmod 755 gradlew && ./gradlew artifactoryPublish
